name: Run Tests
on:
  push:
   branches: [ main ]

env:
  POETRY_VIRTUALENVS_PREFER_ACTIVE_PYTHON: true

jobs:
  build:

    runs-on: ${{ matrix.os }} # Run this job for different versions

    strategy:
      matrix:
        os: [ubuntu-latest] # list of systems to run for. If we build a web-app, usually ubuntu suffices
        python-version: ["3.11"] # list of python versions. Try to always include the latest version
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          poetry install

      - name: Run tests
        run: poetry run pytest --cov=app --cov-report=html --cov-report=json:test-action-coverage.json

      - name: Create coverage badge
        uses: simula-consulting/manual-coverage-badge@v1
        with:
          coverage-json: test-action-coverage.json
          coverage-gist-token: ${{ secrets.GIST_TOKEN }}
          coverage-gist-id: ${{ secrets.GIST_ID }}

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
